### ISSUE TITLE
git branch update/docs

### ISSUE THREAD

**Issue by pevma** [Nimdy/SELKS-Install-from-source#1]
You can now directly pull `master` , no need to pull the `SELKS5` branch specifically :: 

  ``git clone  https://github.com/StamusNetworks/SELKS.git SELKS_CONFIGS     ``

In relation to - https://github.com/Nimdy/SELKS-Install-from-source#clone-git-from-nimdy

**Comment by Nimdy** [comment]
corrected, thank you.
